name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - run: make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install and build fillit-tests
      run: git clone https://github.com/erikpeik/fillit-tests.git && echo ${PWD} > fillit-tests/path.ini
    - name: Run Tests
      run:  bash -c "cd fillit-tests && env TERM=dumb ./test.sh easy" > test.log || cat test.log
    - name: Check Test Results
      run: if grep "FAIL" test.log; then echo "Tests failed"; exit 1; else echo "All tests passed"; fi
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test.log